<?php

return [
    // Storage base on local disk (we stream through controller; no storage:link required)
    'disk' => env('CMS_ASSETS_DISK', 'local'),

    // Where media is stored inside disk
    'base_dir' => env('CMS_ASSETS_BASE_DIR', 'cms_media'),

    // Upload policy. Keep strict mode off initially for compatibility rollout.
    'strict_upload_validation' => (bool) env('CMS_ASSETS_STRICT_UPLOAD_VALIDATION', false),
    'max_upload_size_mb' => (int) env('CMS_ASSETS_MAX_UPLOAD_MB', 100),
    'allowed_mime_types' => array_values(array_filter(array_map('trim', explode(',', (string) env(
        'CMS_ASSETS_ALLOWED_MIME_TYPES',
        'image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,application/pdf,text/plain'
    ))))),
    'allowed_extensions' => array_values(array_filter(array_map('trim', explode(',', (string) env(
        'CMS_ASSETS_ALLOWED_EXTENSIONS',
        'jpg,jpeg,png,webp,gif,mp4,webm,pdf,txt'
    ))))),

    // FFmpeg / FFProbe binaries (default: ffmpeg/ffprobe in PATH; set env to override)
    'ffmpeg' => [
        'ffmpeg.binaries' => [env('FFMPEG_BINARY', 'ffmpeg')],
        'ffprobe.binaries' => [env('FFPROBE_BINARY', 'ffprobe')],
    ],

    // Chunked uploads
    'chunks' => [
        'dir' => env('CMS_ASSETS_CHUNKS_DIR', 'cms_chunks'),
        'ttl_minutes' => (int) env('CMS_ASSETS_CHUNKS_TTL_MINUTES', 60),
        'max_chunk_size_mb' => (int) env('CMS_ASSETS_CHUNK_MAX_MB', 8),
    ],

    // Presets used by /storage/media/{id}/preset/{presetKey}
    'presets' => [
        'thumb' => [
            'w' => 300,
            'h' => 300,
            'fit' => 'crop',
            'q' => 80,
            'format' => 'webp',
        ],
        'large' => [
            'w' => 1600,
            'h' => null,
            'fit' => 'contain',
            'q' => 82,
            'format' => 'jpg',
        ],
        // Video poster: single frame at 1s, JPEG (generated by GenerateVideoPosterJob)
        'poster' => [
            'format' => 'jpg',
        ],
    ],
];
